project_id = "hsnbtetbdaefvvfgoale"

[functions.external-get-farmers]
verify_jwt = false

[functions.external-book-farmer]
verify_jwt = false

[functions.external-booking-webhook]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
