project_id = "hcfcpqlcawbpqtruttsi"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[functions.api-auth]
verify_jwt = false

[functions.external-get-farmers]
verify_jwt = false

[functions.external-book-farmer]
verify_jwt = false

[functions.external-booking-webhook]
verify_jwt = false

[functions.expire-pending-bookings]
verify_jwt = false

[functions.booking-status]
verify_jwt = false

[functions.request-booking]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.main-platform-register-farmer]
verify_jwt = false

[functions.main-platform-get-farmer]
verify_jwt = false

[functions.main-platform-farmer-bookings]
verify_jwt = false

[functions.main-platform-confirm-booking]
verify_jwt = false

[functions.main-platform-booking-status]
verify_jwt = false
