import { createClient } from "npm:@supabase/supabase-js@2";
import { hash, compare } from "npm:bcryptjs@2.4.3";
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const sb = () => createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const j = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { ...cors, "Content-Type": "application/json" } });
const gen = () => crypto.randomUUID() + crypto.randomUUID();
Deno.serve(async (req) => { if (req.method === "OPTIONS") return new Response("ok", { headers: cors }); const url = new URL(req.url); const path = url.pathname.split("/api-auth")[1] || ""; const db = sb();
if (path === "/login" && req.method === "POST") { const { email, password } = await req.json(); const adminEmail = Deno.env.get("ADMIN_EMAIL"); const adminPass = Deno.env.get("ADMIN_PASSWORD"); if (adminEmail && adminPass) { const { data } = await db.from("admins").select("id").eq("email", adminEmail).maybeSingle(); if (!data) await db.from("admins").insert({ email: adminEmail, password_hash: await hash(adminPass, 10) }); }
const { data: admin } = await db.from("admins").select("id,email,password_hash").eq("email", email).maybeSingle(); if (admin?.password_hash && await compare(password, admin.password_hash)) return j({ token: gen(), role: "admin", userId: admin.id, email: admin.email });
const { data: farmer } = await db.from("farmers").select("id,email,password_hash").eq("email", email).maybeSingle(); if (farmer?.password_hash && await compare(password, farmer.password_hash)) return j({ token: gen(), role: "farmer", userId: farmer.id, email: farmer.email });
const { data: buyer } = await db.from("buyers").select("id,email,password_hash,account_status").eq("email", email).maybeSingle(); if (buyer?.account_status === "pending_setup") return j({ error: "Please complete your account setup via the link sent to your WhatsApp." }, 401); if (buyer?.password_hash && await compare(password, buyer.password_hash)) return j({ token: gen(), role: "buyer", userId: buyer.id, email: buyer.email });
return j({ error: "Invalid email or password" }, 401); }
if (path === "/validate-token") { const t = url.searchParams.get("token"); const { data } = await db.from("buyers").select("id").eq("setup_token", t).gt("setup_token_expires_at", new Date().toISOString()).maybeSingle(); return j({ valid: Boolean(data) }); }
if (path === "/resend-setup-link" && req.method === "POST") { const { phone_or_email } = await req.json(); const t = gen(); const { data } = await db.from("buyers").select("id").or(`email.eq.${phone_or_email},phone_number.eq.${phone_or_email}`).maybeSingle(); if (data) await db.from("buyers").update({ setup_token: t, setup_token_expires_at: new Date(Date.now() + 86400000).toISOString() }).eq("id", data.id); console.log("Setup token:", t); return j({ ok: true }); }
if (path === "/complete-setup" && req.method === "POST") { const { token, password } = await req.json(); const { data } = await db.from("buyers").select("id").eq("setup_token", token).gt("setup_token_expires_at", new Date().toISOString()).maybeSingle(); if (!data) return j({ error: "This link has expired." }, 400); await db.from("buyers").update({ password_hash: await hash(password, 10), account_status: "active", setup_token: null, setup_token_expires_at: null }).eq("id", data.id); return j({ ok: true }); }
if (path === "/register-farmer" && req.method === "POST") { const b = await req.json(); const { password, ...rest } = b; const { error } = await db.from("farmers").insert({ ...rest, password_hash: await hash(password, 10) }); if (error) return j({ error: error.message }, 400); return j({ ok: true }); }
return j({ error: "Not found" }, 404); });
