ALTER TABLE public.buyers
  ADD COLUMN IF NOT EXISTS company_name text,
  ADD COLUMN IF NOT EXISTS business_type text,
  ADD COLUMN IF NOT EXISTS primary_county text,
  ADD COLUMN IF NOT EXISTS primary_town text,
  ADD COLUMN IF NOT EXISTS additional_locations jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS varieties_required text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS varieties_other text,
  ADD COLUMN IF NOT EXISTS quantity_per_order numeric,
  ADD COLUMN IF NOT EXISTS quantity_unit text,
  ADD COLUMN IF NOT EXISTS demand_frequency text,
  ADD COLUMN IF NOT EXISTS demand_frequency_custom text,
  ADD COLUMN IF NOT EXISTS quality_preference text,
  ADD COLUMN IF NOT EXISTS quality_specifications text,
  ADD COLUMN IF NOT EXISTS contact_full_name text,
  ADD COLUMN IF NOT EXISTS contact_role text,
  ADD COLUMN IF NOT EXISTS preferred_contact_methods text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS additional_notes text,
  ADD COLUMN IF NOT EXISTS profile_completed boolean NOT NULL DEFAULT false;